services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API : http://localhost:6333/dashboard
      - "6334:6334" # gRPC API
    volumes:
      - ./data/knowledge_base:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    env_file:
      - .env
