services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API : http://localhost:6333/dashboard
      - "6334:6334" # gRPC API
    volumes:
      - ./data/knowledge_base:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
      - ${HOME}/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - SENTENCE_TRANSFORMERS_HOME=/app/data/sentence_transformers
    env_file:
      - .env
